### ISSUE TITLE
Conflicting dependencies with GenieAuthentication

### ISSUE THREAD

**Issue by bbrunaud** [GenieFramework/SearchLightSQLite.jl#4]
Hello

I was not able to install SearchLightSQLite.jl after GenieAuthentication because the first depends on SearchLight 0.20, while the later depends on SearchLight 0.21

thanks!

**Comment by essenciary** [comment]
@bbrunaud Thanks, I'll make a new release to update the dependencies!

**Comment by essenciary** [comment]
This should be fixed now.
